import { useEffect, useState } from "react";
import { fetchAllProducts, fetchBrands, fetchFurnitureCategories, fetchFurnitureProducts } from "../api";
import ProductCard from "./ProductCard";
import ProductDetailModal from "./ProductDetailModal";
export default function FurniturePage(){
const [categoryOpen,setCategoryOpen]=useState(false),[trail,setTrail]=useState([]),[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[loading,setLoading]=useState(false),[selectedProduct,setSelectedProduct]=useState(null),[brandOpen,setBrandOpen]=useState(false),[brands,setBrands]=useState([]),[selectedBrand,setSelectedBrand]=useState(null),[selectedCategoryId,setSelectedCategoryId]=useState(null);
async function loadAllProducts(brand=selectedBrand){setLoading(true);try{setProducts(await fetchAllProducts(brand));}finally{setLoading(false);}}
useEffect(()=>{loadAllProducts(null);},[]);
async function browse(parentId=null,nextTrail=[]){setLoading(true);setTrail(nextTrail);try{setCategories(await fetchFurnitureCategories(parentId));}finally{setLoading(false);}}
async function chooseCategory(category){const nextTrail=[...trail,category];setLoading(true);try{const children=await fetchFurnitureCategories(category.Id);setTrail(nextTrail);setCategories(children);if(!children.length){const [rows,categoryBrands]=await Promise.all([fetchFurnitureProducts(category.Id),fetchBrands(category.Id)]);setSelectedCategoryId(category.Id);setSelectedBrand(null);setBrandOpen(false);setBrands(categoryBrands);setProducts(rows);setCategoryOpen(false);}else setSelectedCategoryId(null);}finally{setLoading(false);}}
async function toggleCategories(){const nextOpen=!categoryOpen;setCategoryOpen(nextOpen);if(nextOpen&&!categories.length)await browse();}
async function toggleBrands(){const nextOpen=!brandOpen;setBrandOpen(nextOpen);if(nextOpen)try{setBrands(await fetchBrands(selectedCategoryId));}catch{setBrandOpen(false);}}
async function chooseBrand(brand){setSelectedBrand(brand);setBrandOpen(false);setLoading(true);try{if(selectedCategoryId){const rows=await fetchFurnitureProducts(selectedCategoryId);setProducts(rows.filter(p=>p.Brand===brand));}else setProducts(await fetchAllProducts(brand));}finally{setLoading(false);}}
function clearFilters(){setTrail([]);setCategories([]);setCategoryOpen(false);setBrandOpen(false);setSelectedBrand(null);setSelectedCategoryId(null);loadAllProducts(null);}
return <section className="max-w-[1280px] mx-auto px-6 py-10"><div className="flex gap-8"><aside className="w-72 shrink-0 bg-white rounded-2xl border border-slate-200 p-6 h-fit"><div className="flex items-center justify-between border-b pb-4"><h2 className="font-bold text-xl">Filtreler</h2><button onClick={clearFilters} className="text-indigo-600 text-sm">Temizle</button></div><button onClick={toggleCategories} className="w-full mt-3 flex justify-between items-center rounded-xl border border-slate-200 px-4 py-3 font-semibold text-left">Kategoriler <span>{categoryOpen?"⌃":"⌄"}</span></button>{categoryOpen&&<div className="mt-3 space-y-2">{loading?<p className="text-sm text-slate-500">Yükleniyor...</p>:categories.map(category=><button key={category.Id} onClick={()=>chooseCategory(category)} className="w-full text-left px-3 py-2 rounded-lg hover:bg-indigo-50 text-sm">{category.Name} ({category.ProductCount}){category.HasChildren?" ›":""}</button>)}</div>}<button onClick={toggleBrands} className="w-full mt-5 flex justify-between items-center rounded-xl border border-slate-200 px-4 py-3 font-semibold text-left">{selectedBrand||"Markalar"} <span>{brandOpen?"⌃":"⌄"}</span></button>{brandOpen&&<div className="mt-3 max-h-56 overflow-y-auto space-y-1">{brands.map(brand=><button key={brand} onClick={()=>chooseBrand(brand)} className="w-full text-left px-3 py-2 rounded-lg hover:bg-indigo-50 text-sm">{brand}</button>)}</div>}</aside><div className="flex-1"><div className="flex gap-2 text-sm text-slate-500 mb-5">{selectedBrand&&<><span>{selectedBrand}</span><span>·</span></>}{trail.length?<><span>{trail[trail.length-1].Name}</span><span>·</span></>:null}<span>{products.length} urun listelendi</span></div>{products.length?<div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-5">{products.map(product=><ProductCard key={product.Id} product={product} onSelectProduct={setSelectedProduct}/>)}</div>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-slate-500">Bu filtrede ürün bulunamadı.</div>}</div></div>{selectedProduct&&<ProductDetailModal masterId={selectedProduct.Id} title={selectedProduct.CanonicalTitle} onClose={()=>setSelectedProduct(null)}/>}</section>;}